version: '3'
services:
  challenge-mysql:
    container_name: challenge-mysql
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: challengedb
      MYSQL_USER: challenge
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - challenge-network
    volumes:
      - challenge-db-volume:/data


volumes:
  challenge-db-volume:

networks:
  challenge-network:
    driver: bridge